/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ReclamationRouteImport } from './routes/reclamation'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedMesDossiersRouteImport } from './routes/_authenticated/mes-dossiers'
import { Route as AuthenticatedPortailRouteImport } from './routes/_authenticated/portail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamationRoute = ReclamationRouteImport.update({
  id: '/reclamation',
  path: '/reclamation',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesDossiersRoute =
  AuthenticatedMesDossiersRouteImport.update({
    id: '/mes-dossiers',
    path: '/mes-dossiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortailRoute = AuthenticatedPortailRouteImport.update({
  id: '/portail',
  path: '/portail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reclamation': typeof ReclamationRoute
  '/suivi': typeof SuiviRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mes-dossiers': typeof AuthenticatedMesDossiersRoute
  '/portail': typeof AuthenticatedPortailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reclamation': typeof ReclamationRoute
  '/suivi': typeof SuiviRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mes-dossiers': typeof AuthenticatedMesDossiersRoute
  '/portail': typeof AuthenticatedPortailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reclamation': typeof ReclamationRoute
  '/suivi': typeof SuiviRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/mes-dossiers': typeof AuthenticatedMesDossiersRoute
  '/_authenticated/portail': typeof AuthenticatedPortailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reclamation'
    | '/suivi'
    | '/agent'
    | '/analytics'
    | '/equipe'
    | '/mes-dossiers'
    | '/portail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reclamation'
    | '/suivi'
    | '/agent'
    | '/analytics'
    | '/equipe'
    | '/mes-dossiers'
    | '/portail'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reclamation'
    | '/suivi'
    | '/_authenticated/agent'
    | '/_authenticated/analytics'
    | '/_authenticated/equipe'
    | '/_authenticated/mes-dossiers'
    | '/_authenticated/portail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReclamationRoute: typeof ReclamationRoute
  SuiviRoute: typeof SuiviRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamation': {
      id: '/reclamation'
      path: '/reclamation'
      fullPath: '/reclamation'
      preLoaderRoute: typeof ReclamationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-dossiers': {
      id: '/_authenticated/mes-dossiers'
      path: '/mes-dossiers'
      fullPath: '/mes-dossiers'
      preLoaderRoute: typeof AuthenticatedMesDossiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portail': {
      id: '/_authenticated/portail'
      path: '/portail'
      fullPath: '/portail'
      preLoaderRoute: typeof AuthenticatedPortailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMesDossiersRoute: typeof AuthenticatedMesDossiersRoute
  AuthenticatedPortailRoute: typeof AuthenticatedPortailRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMesDossiersRoute: AuthenticatedMesDossiersRoute,
  AuthenticatedPortailRoute: AuthenticatedPortailRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReclamationRoute: ReclamationRoute,
  SuiviRoute: SuiviRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
